#!/usr/bin/env bash


manim-slides convert \
    -ccontrols=false \
    -cprogress=true \
    -cshow_slide_number=false \
    -coverview=true \
    -ctouch=true \
    -cview_distance=6 \
    -cmobile_view_distance=4  \
    -chide_cursor_time=1000 \
    TitleAnimation \
    NeuralNetworks \
    ShapeLatentSpace \
    ParallelOpt \
    Unifying \
    RelReps \
    AnglePreserving \
    RelRepsAlgo \
    SemanticSpace \
    LatentMetric \
    RelRepStitching \
    RelRepStitchingVision \
    RelRepStitchingCrossLingual \
    Translation \
    TranslationAlgorithm \
    AffineTransformation \
    TranslationStitching \
    TranslationCrossmodal \
    TranslationOtherResults \
    Formalization \
    Correspondence \
    Limitations \
    BridgeProblem \
    BridgeFramework \
    BridgeResults \
    BootstrappingIntro \
    BootstrappingResults \
    Applying \
    Asif \
    RL \
    Conclusions \
    FutureWorks \
    Unireps \
    CurationIntro \
    CurationPitch \
    CurationWVLP \
    CurationPNKA \
    DataResearch  \
    DataExperimentIntro \
    DataExperiment1 \
    DataExperiment2 \
    DataExperiment3 \
    DataExperiment4 \
    DataExperiment5 \
    DataAdvantages \
    Thanks \
    index.html

